# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://baguswjksn.github.io/blog/" # the url of your github pages

# site information used in page title, meta data etc.
title: "Bagus Muhammad Wijaksono"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Bagus Muhammad Wijaksono
author-bio: i like builds, breaks, and secures things  # change to false to hide
author-image: photo_2025-03-20_08-48-53.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: mailto:baguswijaksono292@gmail.com

# footer information
footer-msg: Bagus Muhammad Wijaksono
footer-msg-link: https://github.com/baguswjksn

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
